/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ztravel.paygate.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 退款响应结果
 */
public class RefundResponse implements org.apache.thrift.TBase<RefundResponse, RefundResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RefundResponse");

  private static final org.apache.thrift.protocol.TField RET_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("retCode", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RET_MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("retMsg", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EXTRA_INFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("extraInfos", org.apache.thrift.protocol.TType.MAP, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RefundResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RefundResponseTupleSchemeFactory());
  }

  /**
   * 返回码, 0000 代表处理成功
   */
  public String retCode; // required
  /**
   * 返回信息，是对返回码的详细描述
   */
  public String retMsg; // optional
  /**
   * 退款请求时使用的参数等信息
   */
  public Map<String,String> extraInfos; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 返回码, 0000 代表处理成功
     */
    RET_CODE((short)1, "retCode"),
    /**
     * 返回信息，是对返回码的详细描述
     */
    RET_MSG((short)2, "retMsg"),
    /**
     * 退款请求时使用的参数等信息
     */
    EXTRA_INFOS((short)3, "extraInfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RET_CODE
          return RET_CODE;
        case 2: // RET_MSG
          return RET_MSG;
        case 3: // EXTRA_INFOS
          return EXTRA_INFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.RET_MSG,_Fields.EXTRA_INFOS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RET_CODE, new org.apache.thrift.meta_data.FieldMetaData("retCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RET_MSG, new org.apache.thrift.meta_data.FieldMetaData("retMsg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EXTRA_INFOS, new org.apache.thrift.meta_data.FieldMetaData("extraInfos", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RefundResponse.class, metaDataMap);
  }

  public RefundResponse() {
  }

  public RefundResponse(
    String retCode)
  {
    this();
    this.retCode = retCode;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RefundResponse(RefundResponse other) {
    if (other.isSetRetCode()) {
      this.retCode = other.retCode;
    }
    if (other.isSetRetMsg()) {
      this.retMsg = other.retMsg;
    }
    if (other.isSetExtraInfos()) {
      Map<String,String> __this__extraInfos = new HashMap<String,String>();
      for (Map.Entry<String, String> other_element : other.extraInfos.entrySet()) {

        String other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        String __this__extraInfos_copy_key = other_element_key;

        String __this__extraInfos_copy_value = other_element_value;

        __this__extraInfos.put(__this__extraInfos_copy_key, __this__extraInfos_copy_value);
      }
      this.extraInfos = __this__extraInfos;
    }
  }

  public RefundResponse deepCopy() {
    return new RefundResponse(this);
  }

  @Override
  public void clear() {
    this.retCode = null;
    this.retMsg = null;
    this.extraInfos = null;
  }

  /**
   * 返回码, 0000 代表处理成功
   */
  public String getRetCode() {
    return this.retCode;
  }

  /**
   * 返回码, 0000 代表处理成功
   */
  public RefundResponse setRetCode(String retCode) {
    this.retCode = retCode;
    return this;
  }

  public void unsetRetCode() {
    this.retCode = null;
  }

  /** Returns true if field retCode is set (has been assigned a value) and false otherwise */
  public boolean isSetRetCode() {
    return this.retCode != null;
  }

  public void setRetCodeIsSet(boolean value) {
    if (!value) {
      this.retCode = null;
    }
  }

  /**
   * 返回信息，是对返回码的详细描述
   */
  public String getRetMsg() {
    return this.retMsg;
  }

  /**
   * 返回信息，是对返回码的详细描述
   */
  public RefundResponse setRetMsg(String retMsg) {
    this.retMsg = retMsg;
    return this;
  }

  public void unsetRetMsg() {
    this.retMsg = null;
  }

  /** Returns true if field retMsg is set (has been assigned a value) and false otherwise */
  public boolean isSetRetMsg() {
    return this.retMsg != null;
  }

  public void setRetMsgIsSet(boolean value) {
    if (!value) {
      this.retMsg = null;
    }
  }

  public int getExtraInfosSize() {
    return (this.extraInfos == null) ? 0 : this.extraInfos.size();
  }

  public void putToExtraInfos(String key, String val) {
    if (this.extraInfos == null) {
      this.extraInfos = new HashMap<String,String>();
    }
    this.extraInfos.put(key, val);
  }

  /**
   * 退款请求时使用的参数等信息
   */
  public Map<String,String> getExtraInfos() {
    return this.extraInfos;
  }

  /**
   * 退款请求时使用的参数等信息
   */
  public RefundResponse setExtraInfos(Map<String,String> extraInfos) {
    this.extraInfos = extraInfos;
    return this;
  }

  public void unsetExtraInfos() {
    this.extraInfos = null;
  }

  /** Returns true if field extraInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetExtraInfos() {
    return this.extraInfos != null;
  }

  public void setExtraInfosIsSet(boolean value) {
    if (!value) {
      this.extraInfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RET_CODE:
      if (value == null) {
        unsetRetCode();
      } else {
        setRetCode((String)value);
      }
      break;

    case RET_MSG:
      if (value == null) {
        unsetRetMsg();
      } else {
        setRetMsg((String)value);
      }
      break;

    case EXTRA_INFOS:
      if (value == null) {
        unsetExtraInfos();
      } else {
        setExtraInfos((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RET_CODE:
      return getRetCode();

    case RET_MSG:
      return getRetMsg();

    case EXTRA_INFOS:
      return getExtraInfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RET_CODE:
      return isSetRetCode();
    case RET_MSG:
      return isSetRetMsg();
    case EXTRA_INFOS:
      return isSetExtraInfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RefundResponse)
      return this.equals((RefundResponse)that);
    return false;
  }

  public boolean equals(RefundResponse that) {
    if (that == null)
      return false;

    boolean this_present_retCode = true && this.isSetRetCode();
    boolean that_present_retCode = true && that.isSetRetCode();
    if (this_present_retCode || that_present_retCode) {
      if (!(this_present_retCode && that_present_retCode))
        return false;
      if (!this.retCode.equals(that.retCode))
        return false;
    }

    boolean this_present_retMsg = true && this.isSetRetMsg();
    boolean that_present_retMsg = true && that.isSetRetMsg();
    if (this_present_retMsg || that_present_retMsg) {
      if (!(this_present_retMsg && that_present_retMsg))
        return false;
      if (!this.retMsg.equals(that.retMsg))
        return false;
    }

    boolean this_present_extraInfos = true && this.isSetExtraInfos();
    boolean that_present_extraInfos = true && that.isSetExtraInfos();
    if (this_present_extraInfos || that_present_extraInfos) {
      if (!(this_present_extraInfos && that_present_extraInfos))
        return false;
      if (!this.extraInfos.equals(that.extraInfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(RefundResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    RefundResponse typedOther = (RefundResponse)other;

    lastComparison = Boolean.valueOf(isSetRetCode()).compareTo(typedOther.isSetRetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retCode, typedOther.retCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRetMsg()).compareTo(typedOther.isSetRetMsg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetMsg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retMsg, typedOther.retMsg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExtraInfos()).compareTo(typedOther.isSetExtraInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExtraInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.extraInfos, typedOther.extraInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RefundResponse(");
    boolean first = true;

    sb.append("retCode:");
    if (this.retCode == null) {
      sb.append("null");
    } else {
      sb.append(this.retCode);
    }
    first = false;
    if (isSetRetMsg()) {
      if (!first) sb.append(", ");
      sb.append("retMsg:");
      if (this.retMsg == null) {
        sb.append("null");
      } else {
        sb.append(this.retMsg);
      }
      first = false;
    }
    if (isSetExtraInfos()) {
      if (!first) sb.append(", ");
      sb.append("extraInfos:");
      if (this.extraInfos == null) {
        sb.append("null");
      } else {
        sb.append(this.extraInfos);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (retCode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'retCode' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RefundResponseStandardSchemeFactory implements SchemeFactory {
    public RefundResponseStandardScheme getScheme() {
      return new RefundResponseStandardScheme();
    }
  }

  private static class RefundResponseStandardScheme extends StandardScheme<RefundResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RefundResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RET_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.retCode = iprot.readString();
              struct.setRetCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RET_MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.retMsg = iprot.readString();
              struct.setRetMsgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXTRA_INFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map48 = iprot.readMapBegin();
                struct.extraInfos = new HashMap<String,String>(2*_map48.size);
                for (int _i49 = 0; _i49 < _map48.size; ++_i49)
                {
                  String _key50; // required
                  String _val51; // required
                  _key50 = iprot.readString();
                  _val51 = iprot.readString();
                  struct.extraInfos.put(_key50, _val51);
                }
                iprot.readMapEnd();
              }
              struct.setExtraInfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RefundResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.retCode != null) {
        oprot.writeFieldBegin(RET_CODE_FIELD_DESC);
        oprot.writeString(struct.retCode);
        oprot.writeFieldEnd();
      }
      if (struct.retMsg != null) {
        if (struct.isSetRetMsg()) {
          oprot.writeFieldBegin(RET_MSG_FIELD_DESC);
          oprot.writeString(struct.retMsg);
          oprot.writeFieldEnd();
        }
      }
      if (struct.extraInfos != null) {
        if (struct.isSetExtraInfos()) {
          oprot.writeFieldBegin(EXTRA_INFOS_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.extraInfos.size()));
            for (Map.Entry<String, String> _iter52 : struct.extraInfos.entrySet())
            {
              oprot.writeString(_iter52.getKey());
              oprot.writeString(_iter52.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RefundResponseTupleSchemeFactory implements SchemeFactory {
    public RefundResponseTupleScheme getScheme() {
      return new RefundResponseTupleScheme();
    }
  }

  private static class RefundResponseTupleScheme extends TupleScheme<RefundResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RefundResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.retCode);
      BitSet optionals = new BitSet();
      if (struct.isSetRetMsg()) {
        optionals.set(0);
      }
      if (struct.isSetExtraInfos()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRetMsg()) {
        oprot.writeString(struct.retMsg);
      }
      if (struct.isSetExtraInfos()) {
        {
          oprot.writeI32(struct.extraInfos.size());
          for (Map.Entry<String, String> _iter53 : struct.extraInfos.entrySet())
          {
            oprot.writeString(_iter53.getKey());
            oprot.writeString(_iter53.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RefundResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.retCode = iprot.readString();
      struct.setRetCodeIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.retMsg = iprot.readString();
        struct.setRetMsgIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map54 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.extraInfos = new HashMap<String,String>(2*_map54.size);
          for (int _i55 = 0; _i55 < _map54.size; ++_i55)
          {
            String _key56; // required
            String _val57; // required
            _key56 = iprot.readString();
            _val57 = iprot.readString();
            struct.extraInfos.put(_key56, _val57);
          }
        }
        struct.setExtraInfosIsSet(true);
      }
    }
  }

}

