$axure.loadCurrentPage({
  "url":"会员详情.html",
  "generationDate":new Date(1427940051261.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55eb43e0294a4d12b052e3feb3322d78",
    "type":"Axure:Page",
    "name":"会员详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1e09f097e524f8d83d5bfc8ab4efa69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"solid",
              "color":0xAAF2F2F2},
            "location":{
              "x":100,
              "y":0},
            "size":{
              "width":1100,
              "height":1370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba6f3c92deed41b5be36cccd478e0a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"solid",
                  "color":0xAAF2F2F2},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":1100,
                  "height":1370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员详情/u0.png"}},
{
          "id":"b516f3a9248a41e99923cbbb03859d40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":270,
              "y":135},
            "size":{
              "width":930,
              "height":700},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF62CA96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e73e38c43ff4171ab96450b20662d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":270,
                  "y":135},
                "size":{
                  "width":930,
                  "height":700},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF62CA96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员详情/u2.png"}},
{
          "id":"c129e5958c0a4df1bd2c726eac8009a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"solid",
              "color":0xFF62CA96},
            "location":{
              "x":100,
              "y":0},
            "size":{
              "width":1100,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84c23031f36b4385a3e9840d339032f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF62CA96},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":1100,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员管理/u4.png"}},
{
          "id":"1b579d74b7dd42c59ca2c26b50bdbfde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":213,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2522a107050e4548912a0abc6938591e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":213,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b38cc01189f47368c94eee651e74b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":308,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f7cd47b4764644b70620bef6bb1fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":308,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f38cdf123560481a9ac3abbbd53150af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":404,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"405037f1604641279987852ed3572011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":404,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711a621b03834848818c79862c24fde9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":499,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c82325ab4bd8404f9283ea6725d09d3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":499,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df0824060840478b8dcf2b694302a7c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF216141,
              "opacity":1},
            "location":{
              "x":594,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e1656548c084b35bc67a8caa2a5117e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF216141,
                  "opacity":1},
                "location":{
                  "x":594,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员管理/u14.png"}},
{
          "id":"5666e0fb6518431fb3036a240266de40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":690,
              "y":43},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df109c644ae04882bd03d3d2df91fa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":690,
                  "y":43},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca6d9a30184b415597b26d49292dc7ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":820,
              "y":43},
            "size":{
              "width":95,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5073c36edfe4da2a6e1484d9cd5cf57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":820,
                  "y":43},
                "size":{
                  "width":95,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6126e5e65c534c45ae9d937196c1ec72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":116,
              "y":11},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4e8d474aa2946969c4b667ad8427565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":116,
                  "y":11},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 主页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u22.png"}},
{
          "id":"d29269c161c1489ab894b7a6ea350a35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":1019,
              "y":12},
            "size":{
              "width":26,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140a2d8e6bc846179587b5ed14fff7d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":1019,
                  "y":12},
                "size":{
                  "width":26,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b9943294af14c5096efec8d0d5d45b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":982,
              "y":10},
            "size":{
              "width":29,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6d4031117847d591d2b87f271d0aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":982,
                  "y":10},
                "size":{
                  "width":29,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u28.png"}},
{
          "id":"45080e2d0c22415491c11fc53cf75572",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":913,
              "y":14},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e54d9c93e8b493ab1da33a067477454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":913,
                  "y":14},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04d0aa7bfe3040c9b4193dc9badc3b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"13px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":1067,
              "y":14},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5971f8c05104f0e98f2bd772b64c1af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"13px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":1067,
                  "y":14},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"297f2f73b0f44817b2f0e8fe5607e373",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"13px",
            "fontWeight":"400",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":1145,
              "y":14},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6cf645d72164fa0ad34f918ef346c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"13px",
                "fontWeight":"400",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":1145,
                  "y":14},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ab3ccdf505d448095ce3b7b958fb21f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":308,
              "y":188},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d3c2c8db8444b790ab522a4263827d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":308,
                  "y":188},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c320a6433340bc809503e683feecef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":308,
              "y":222},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0018e87a923b4a278f69bab2709339a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":308,
                  "y":222},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"663c3f2ca66c4058acf8f5805eba067d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":309,
              "y":256},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4364f55619fa47e29dfdffcc2a8b356e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":309,
                  "y":256},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"324de91556734967af9318d718dbef1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":309,
              "y":358},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f209b9296d4f20b4e7ebffd32390f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":309,
                  "y":358},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1fa77d53861443189a92d6a73b45c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":308,
              "y":290},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b7478b2d1b4970a6a6ba4efef9272c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":308,
                  "y":290},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f918fb610e8a4144bca7290dc956d41b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":308,
              "y":324},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85ba8e2e00c47ada78c753cfc5c22de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":308,
                  "y":324},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bb8d7c0af364bc1b8cfa20db0527791",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":309,
              "y":392},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f488991049bf414a8de5cabfe264ce97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":309,
                  "y":392},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d64a32b69874fe88efef77a4e0bcdc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":188},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7843593a8f404c6c9dc598fe7b0f549d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":188},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56fde874b3dd45bf84ce0038f95e490e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":222},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce99aad9cc104caa81cf77a09d1d7ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":222},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7c193f0e31940748d3919703f65fe02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":256},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2684f57535ae4baeb81b9a56d47c119d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":256},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46cd341f4933486483f969c2e1bec236",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":358},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75823d6a17644778bde365bb8d7e1577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":358},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97927a97cb094980b7a10c63f66d4420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":395,
              "y":290},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38ecef8ed534d15935dc421a88d774f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":290},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3436d88f12a5464ba75992c27d9fb800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":395,
              "y":324},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6268c62de80b4681baeee6d4ecded23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":324},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a1f3261436849029e2084ca03e1f8be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":392},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ffae1540e474396bf1b782b0b3740b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":392},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07fd7163ed3c46bdabe70af377b842ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":309,
              "y":426},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb453ec933a4bc18d735ea32b6647bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":309,
                  "y":426},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b404adbe2063445b9e02d208950ce8cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":426},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a69e3bf2e7bb43e98974cb86ef7f1e27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":426},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf9f2d4a9c40463a9d528f52a5d97401",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":309,
              "y":460},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"907882009fec4021a850301613f460e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":309,
                  "y":460},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fefad651036746ff8c711873360cfe64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":396,
              "y":460},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e94add4df7774e5fa3f0f634cdb1c964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":396,
                  "y":460},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b94ea8dbca34987837fd1fb0e077714",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":664,
              "y":191},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7eba8a609244bd9fac78e0c70f2994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":664,
                  "y":191},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc1901bf1244780a6e000226072653d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":313,
              "y":555},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f27e11521741b099662de81356ec8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":313,
                  "y":555},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd7e60ab2ad24a21a0ebc8db995cda89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":313,
              "y":590},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375c8f4a3d3f4a08a733180b50c1008a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":313,
                  "y":590},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc1fc31973a840969b10a0280af9fde0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":555},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d34d920b2d449119d30a19ea9e56e2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":555,
                  "y":555},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6824a6ea2be54ce0ac69251fc26e5963",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":590},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa99913e0bd4020a23b92a000f6f4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":555,
                  "y":590},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f39c2e8aab54d4faeeac17d6ee46003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":313,
              "y":626},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb66b4e2913d4125a1b6451a1c10b094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":313,
                  "y":626},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"823822dbb06b4adda795850eb6a0f46d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":626},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e396aee8cd4345a88be6e9cd4c118b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":555,
                  "y":626},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"994488cb300c426ca37f25ff3db85449",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":706.5,
              "y":188},
            "size":{
              "width":140,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff9019dbe6d46c8a9aac1ba1fd812db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":706.5,
                  "y":188},
                "size":{
                  "width":140,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员详情/u82.png"}},
{
          "id":"d1b008dfdba341ed9e16dffb276e7f74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF363636,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF8ED9B4},
            "location":{
              "x":100,
              "y":253},
            "size":{
              "width":160,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"969f73dfc42d4264b52cccf2548acd2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8ED9B4},
                "location":{
                  "x":100,
                  "y":253},
                "size":{
                  "width":160,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 常用旅客信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"常用旅客信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员详情/u84.png"}},
{
          "id":"b2cd1cbb6c3e4755ab4ec3bccfd0b530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF349E69},
            "location":{
              "x":100,
              "y":177},
            "size":{
              "width":160,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8f6daf819041e890c049247c9eb975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF349E69},
                "location":{
                  "x":100,
                  "y":177},
                "size":{
                  "width":160,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 会员详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"会员详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员详情/u86.png"}},
{
          "id":"09ce8492a5f240eabe8d7b34f451a2f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF8ED9B4},
            "location":{
              "x":100,
              "y":215},
            "size":{
              "width":160,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56778b93bcb244be94029464517b9771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8ED9B4},
                "location":{
                  "x":100,
                  "y":215},
                "size":{
                  "width":160,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员详情/u84.png"}},
{
          "id":"23da898964b643f98fbfdcaa8fc061b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"18px",
            "location":{
              "x":123,
              "y":142},
            "size":{
              "width":1,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"159c1ae96805423c8380815a50a003ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"18px",
                "location":{
                  "x":123,
                  "y":142},
                "size":{
                  "width":1,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29ee2483a2594f66a4f6950bbfa77be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":434,
              "y":555},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d5c2e3acd5e451ca43e315c23a34d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":434,
                  "y":555},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7de2bbce0784c50bdc3b5fb1c58ded6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":434,
              "y":590},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad9eb6198f97426ea59129a108469c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":434,
                  "y":590},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9902cd5444747fda2dcbdf6c2c59f29",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":495},
            "size":{
              "width":403,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员详情/u96_line.png"}},
{
          "id":"c79574a96a5f4ce7adcb49eca4b0be53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"18px",
            "location":{
              "x":313,
              "y":511},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5bc1990ec424534b2b9f65dfe0f74d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"18px",
                "location":{
                  "x":313,
                  "y":511},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4472eb0fb3324c3b8a67cee6e8b7049c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":440,
              "y":626},
            "size":{
              "width":41,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6527b74a11d0478ea71ddd40de6b86c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":440,
                  "y":626},
                "size":{
                  "width":41,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c60fc9578e7f48c183e9012d80459912",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":279,
              "y":145},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27274c206b854ff4bd547c1e9c80df7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":279,
                  "y":145},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99cfdb5a5cf747a2ba7aeadf274a20d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":100,
              "y":80},
            "size":{
              "width":1100,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f070c144d192496aa729720ff2d24d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":1100,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员管理/u280.png"}},
{
          "id":"8d4bd980bb194d2d9aab30d1e2b56b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336633,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":548,
              "y":81},
            "size":{
              "width":95,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7772a0cfe1d4bbba052b7dbe807a2ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336633,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":548,
                  "y":81},
                "size":{
                  "width":95,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa406457faef43679c8721d9f36a138b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":642,
              "y":81},
            "size":{
              "width":95,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be796b4aafa84ed89f124076d64286d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":642,
                  "y":81},
                "size":{
                  "width":95,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3c12f0237244ce7a072f83a1bcc14e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":134,
              "y":134},
            "size":{
              "width":106,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3733631ee85947ed9cde54373d329892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":134,
                  "y":134},
                "size":{
                  "width":106,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员详情/u109.png"}},
{
          "id":"75060e410cc74d768f1b884ac02e1efd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":143},
            "size":{
              "width":21,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF282828}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/会员详情/u111_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员详情/u111_line.png"}},
{
          "id":"60c16bc333274b22a012321272d6c5e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":737,
              "y":81},
            "size":{
              "width":95,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4ab12fabae0424ba0c8701441589aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":737,
                  "y":81},
                "size":{
                  "width":95,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d1e09f097e524f8d83d5bfc8ab4efa69":{
      "scriptId":"u0"},
    "ba6f3c92deed41b5be36cccd478e0a95":{
      "scriptId":"u1"},
    "b516f3a9248a41e99923cbbb03859d40":{
      "scriptId":"u2"},
    "7e73e38c43ff4171ab96450b20662d31":{
      "scriptId":"u3"},
    "c129e5958c0a4df1bd2c726eac8009a5":{
      "scriptId":"u4"},
    "84c23031f36b4385a3e9840d339032f5":{
      "scriptId":"u5"},
    "1b579d74b7dd42c59ca2c26b50bdbfde":{
      "scriptId":"u6"},
    "2522a107050e4548912a0abc6938591e":{
      "scriptId":"u7"},
    "8b38cc01189f47368c94eee651e74b1a":{
      "scriptId":"u8"},
    "f1f7cd47b4764644b70620bef6bb1fa2":{
      "scriptId":"u9"},
    "f38cdf123560481a9ac3abbbd53150af":{
      "scriptId":"u10"},
    "405037f1604641279987852ed3572011":{
      "scriptId":"u11"},
    "711a621b03834848818c79862c24fde9":{
      "scriptId":"u12"},
    "c82325ab4bd8404f9283ea6725d09d3e":{
      "scriptId":"u13"},
    "df0824060840478b8dcf2b694302a7c4":{
      "scriptId":"u14"},
    "6e1656548c084b35bc67a8caa2a5117e":{
      "scriptId":"u15"},
    "5666e0fb6518431fb3036a240266de40":{
      "scriptId":"u16"},
    "df109c644ae04882bd03d3d2df91fa19":{
      "scriptId":"u17"},
    "ca6d9a30184b415597b26d49292dc7ab":{
      "scriptId":"u18"},
    "b5073c36edfe4da2a6e1484d9cd5cf57":{
      "scriptId":"u19"},
    "6126e5e65c534c45ae9d937196c1ec72":{
      "scriptId":"u20"},
    "c4e8d474aa2946969c4b667ad8427565":{
      "scriptId":"u21"},
    "d29269c161c1489ab894b7a6ea350a35":{
      "scriptId":"u22"},
    "140a2d8e6bc846179587b5ed14fff7d9":{
      "scriptId":"u23"},
    "8b9943294af14c5096efec8d0d5d45b7":{
      "scriptId":"u24"},
    "df6d4031117847d591d2b87f271d0aa3":{
      "scriptId":"u25"},
    "45080e2d0c22415491c11fc53cf75572":{
      "scriptId":"u26"},
    "0e54d9c93e8b493ab1da33a067477454":{
      "scriptId":"u27"},
    "04d0aa7bfe3040c9b4193dc9badc3b1a":{
      "scriptId":"u28"},
    "a5971f8c05104f0e98f2bd772b64c1af":{
      "scriptId":"u29"},
    "297f2f73b0f44817b2f0e8fe5607e373":{
      "scriptId":"u30"},
    "a6cf645d72164fa0ad34f918ef346c90":{
      "scriptId":"u31"},
    "0ab3ccdf505d448095ce3b7b958fb21f":{
      "scriptId":"u32"},
    "01d3c2c8db8444b790ab522a4263827d":{
      "scriptId":"u33"},
    "68c320a6433340bc809503e683feecef":{
      "scriptId":"u34"},
    "0018e87a923b4a278f69bab2709339a8":{
      "scriptId":"u35"},
    "663c3f2ca66c4058acf8f5805eba067d":{
      "scriptId":"u36"},
    "4364f55619fa47e29dfdffcc2a8b356e":{
      "scriptId":"u37"},
    "324de91556734967af9318d718dbef1b":{
      "scriptId":"u38"},
    "82f209b9296d4f20b4e7ebffd32390f0":{
      "scriptId":"u39"},
    "b1fa77d53861443189a92d6a73b45c1a":{
      "scriptId":"u40"},
    "90b7478b2d1b4970a6a6ba4efef9272c":{
      "scriptId":"u41"},
    "f918fb610e8a4144bca7290dc956d41b":{
      "scriptId":"u42"},
    "f85ba8e2e00c47ada78c753cfc5c22de":{
      "scriptId":"u43"},
    "9bb8d7c0af364bc1b8cfa20db0527791":{
      "scriptId":"u44"},
    "f488991049bf414a8de5cabfe264ce97":{
      "scriptId":"u45"},
    "5d64a32b69874fe88efef77a4e0bcdc5":{
      "scriptId":"u46"},
    "7843593a8f404c6c9dc598fe7b0f549d":{
      "scriptId":"u47"},
    "56fde874b3dd45bf84ce0038f95e490e":{
      "scriptId":"u48"},
    "ce99aad9cc104caa81cf77a09d1d7ef5":{
      "scriptId":"u49"},
    "b7c193f0e31940748d3919703f65fe02":{
      "scriptId":"u50"},
    "2684f57535ae4baeb81b9a56d47c119d":{
      "scriptId":"u51"},
    "46cd341f4933486483f969c2e1bec236":{
      "scriptId":"u52"},
    "75823d6a17644778bde365bb8d7e1577":{
      "scriptId":"u53"},
    "97927a97cb094980b7a10c63f66d4420":{
      "scriptId":"u54"},
    "e38ecef8ed534d15935dc421a88d774f":{
      "scriptId":"u55"},
    "3436d88f12a5464ba75992c27d9fb800":{
      "scriptId":"u56"},
    "6268c62de80b4681baeee6d4ecded23d":{
      "scriptId":"u57"},
    "6a1f3261436849029e2084ca03e1f8be":{
      "scriptId":"u58"},
    "3ffae1540e474396bf1b782b0b3740b3":{
      "scriptId":"u59"},
    "07fd7163ed3c46bdabe70af377b842ea":{
      "scriptId":"u60"},
    "2bb453ec933a4bc18d735ea32b6647bc":{
      "scriptId":"u61"},
    "b404adbe2063445b9e02d208950ce8cf":{
      "scriptId":"u62"},
    "a69e3bf2e7bb43e98974cb86ef7f1e27":{
      "scriptId":"u63"},
    "cf9f2d4a9c40463a9d528f52a5d97401":{
      "scriptId":"u64"},
    "907882009fec4021a850301613f460e3":{
      "scriptId":"u65"},
    "fefad651036746ff8c711873360cfe64":{
      "scriptId":"u66"},
    "e94add4df7774e5fa3f0f634cdb1c964":{
      "scriptId":"u67"},
    "6b94ea8dbca34987837fd1fb0e077714":{
      "scriptId":"u68"},
    "af7eba8a609244bd9fac78e0c70f2994":{
      "scriptId":"u69"},
    "7dc1901bf1244780a6e000226072653d":{
      "scriptId":"u70"},
    "39f27e11521741b099662de81356ec8b":{
      "scriptId":"u71"},
    "cd7e60ab2ad24a21a0ebc8db995cda89":{
      "scriptId":"u72"},
    "375c8f4a3d3f4a08a733180b50c1008a":{
      "scriptId":"u73"},
    "dc1fc31973a840969b10a0280af9fde0":{
      "scriptId":"u74"},
    "7d34d920b2d449119d30a19ea9e56e2e":{
      "scriptId":"u75"},
    "6824a6ea2be54ce0ac69251fc26e5963":{
      "scriptId":"u76"},
    "2fa99913e0bd4020a23b92a000f6f4f9":{
      "scriptId":"u77"},
    "5f39c2e8aab54d4faeeac17d6ee46003":{
      "scriptId":"u78"},
    "eb66b4e2913d4125a1b6451a1c10b094":{
      "scriptId":"u79"},
    "823822dbb06b4adda795850eb6a0f46d":{
      "scriptId":"u80"},
    "e396aee8cd4345a88be6e9cd4c118b05":{
      "scriptId":"u81"},
    "994488cb300c426ca37f25ff3db85449":{
      "scriptId":"u82"},
    "7ff9019dbe6d46c8a9aac1ba1fd812db":{
      "scriptId":"u83"},
    "d1b008dfdba341ed9e16dffb276e7f74":{
      "scriptId":"u84"},
    "969f73dfc42d4264b52cccf2548acd2d":{
      "scriptId":"u85"},
    "b2cd1cbb6c3e4755ab4ec3bccfd0b530":{
      "scriptId":"u86"},
    "3d8f6daf819041e890c049247c9eb975":{
      "scriptId":"u87"},
    "09ce8492a5f240eabe8d7b34f451a2f0":{
      "scriptId":"u88"},
    "56778b93bcb244be94029464517b9771":{
      "scriptId":"u89"},
    "23da898964b643f98fbfdcaa8fc061b6":{
      "scriptId":"u90"},
    "159c1ae96805423c8380815a50a003ec":{
      "scriptId":"u91"},
    "29ee2483a2594f66a4f6950bbfa77be8":{
      "scriptId":"u92"},
    "4d5c2e3acd5e451ca43e315c23a34d94":{
      "scriptId":"u93"},
    "b7de2bbce0784c50bdc3b5fb1c58ded6":{
      "scriptId":"u94"},
    "ad9eb6198f97426ea59129a108469c1c":{
      "scriptId":"u95"},
    "c9902cd5444747fda2dcbdf6c2c59f29":{
      "scriptId":"u96"},
    "c79574a96a5f4ce7adcb49eca4b0be53":{
      "scriptId":"u97"},
    "d5bc1990ec424534b2b9f65dfe0f74d9":{
      "scriptId":"u98"},
    "4472eb0fb3324c3b8a67cee6e8b7049c":{
      "scriptId":"u99"},
    "6527b74a11d0478ea71ddd40de6b86c2":{
      "scriptId":"u100"},
    "c60fc9578e7f48c183e9012d80459912":{
      "scriptId":"u101"},
    "27274c206b854ff4bd547c1e9c80df7d":{
      "scriptId":"u102"},
    "99cfdb5a5cf747a2ba7aeadf274a20d9":{
      "scriptId":"u103"},
    "f070c144d192496aa729720ff2d24d7e":{
      "scriptId":"u104"},
    "8d4bd980bb194d2d9aab30d1e2b56b33":{
      "scriptId":"u105"},
    "c7772a0cfe1d4bbba052b7dbe807a2ab":{
      "scriptId":"u106"},
    "fa406457faef43679c8721d9f36a138b":{
      "scriptId":"u107"},
    "be796b4aafa84ed89f124076d64286d0":{
      "scriptId":"u108"},
    "a3c12f0237244ce7a072f83a1bcc14e4":{
      "scriptId":"u109"},
    "3733631ee85947ed9cde54373d329892":{
      "scriptId":"u110"},
    "75060e410cc74d768f1b884ac02e1efd":{
      "scriptId":"u111"},
    "60c16bc333274b22a012321272d6c5e2":{
      "scriptId":"u112"},
    "a4ab12fabae0424ba0c8701441589aab":{
      "scriptId":"u113"}}});