package com.ztravel.operator.financeMantain.po;
import java.util.Date;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.account_bank
     *
     * @mbggenerated
     */
    private String accountBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.settlement_period
     *
     * @mbggenerated
     */
    private String settlementPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.bussiness_contacts
     *
     * @mbggenerated
     */
    private String bussinessContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.inner_contacts
     *
     * @mbggenerated
     */
    private String innerContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.t_supplier.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.supplier_name
     *
     * @return the value of payment.t_supplier.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.supplier_name
     *
     * @param supplierName the value for payment.t_supplier.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.account_bank
     *
     * @return the value of payment.t_supplier.account_bank
     *
     * @mbggenerated
     */
    public String getAccountBank() {
        return accountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.account_bank
     *
     * @param accountBank the value for payment.t_supplier.account_bank
     *
     * @mbggenerated
     */
    public void setAccountBank(String accountBank) {
        this.accountBank = accountBank == null ? null : accountBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.account_name
     *
     * @return the value of payment.t_supplier.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.account_name
     *
     * @param accountName the value for payment.t_supplier.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.account
     *
     * @return the value of payment.t_supplier.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.account
     *
     * @param account the value for payment.t_supplier.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.settlement_period
     *
     * @return the value of payment.t_supplier.settlement_period
     *
     * @mbggenerated
     */
    public String getSettlementPeriod() {
        return settlementPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.settlement_period
     *
     * @param settlementPeriod the value for payment.t_supplier.settlement_period
     *
     * @mbggenerated
     */
    public void setSettlementPeriod(String settlementPeriod) {
        this.settlementPeriod = settlementPeriod == null ? null : settlementPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.bussiness_contacts
     *
     * @return the value of payment.t_supplier.bussiness_contacts
     *
     * @mbggenerated
     */
    public String getBussinessContacts() {
        return bussinessContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.bussiness_contacts
     *
     * @param bussinessContacts the value for payment.t_supplier.bussiness_contacts
     *
     * @mbggenerated
     */
    public void setBussinessContacts(String bussinessContacts) {
        this.bussinessContacts = bussinessContacts == null ? null : bussinessContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.phone
     *
     * @return the value of payment.t_supplier.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.phone
     *
     * @param phone the value for payment.t_supplier.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.fax
     *
     * @return the value of payment.t_supplier.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.fax
     *
     * @param fax the value for payment.t_supplier.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.email
     *
     * @return the value of payment.t_supplier.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.email
     *
     * @param email the value for payment.t_supplier.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.inner_contacts
     *
     * @return the value of payment.t_supplier.inner_contacts
     *
     * @mbggenerated
     */
    public String getInnerContacts() {
        return innerContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.inner_contacts
     *
     * @param innerContacts the value for payment.t_supplier.inner_contacts
     *
     * @mbggenerated
     */
    public void setInnerContacts(String innerContacts) {
        this.innerContacts = innerContacts == null ? null : innerContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.create_time
     *
     * @return the value of payment.t_supplier.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.create_time
     *
     * @param createTime the value for payment.t_supplier.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.t_supplier.update_time
     *
     * @return the value of payment.t_supplier.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.t_supplier.update_time
     *
     * @param updateTime the value for payment.t_supplier.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}
}